# Generated by Django 6.0.3 on 2026-04-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='consultation_fee_snapshot',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Phí khám tại thời điểm tạo hóa đơn (snapshot để tránh thay đổi)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Mã giao dịch từ cổng thanh toán', max_length=100),
        ),
        migrations.AddField(
            model_name='billing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
