# Generated by Django 6.0.3 on 2026-04-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_billing_snapshot_fields'),
        ('doctors', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='checked_in',
            field=models.BooleanField(default=False, help_text='Đã check-in khi đến khám'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BookingConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(help_text='Mã xác nhận', max_length=20, unique=True)),
                ('qr_data', models.TextField(blank=True, help_text='Dữ liệu cho QR code (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Phiếu khám',
                'verbose_name_plural': 'Phiếu khám',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.TextField(help_text='Chẩn đoán')),
                ('notes', models.TextField(blank=True, help_text='Ghi chú chuyên môn')),
                ('treatment_plan', models.TextField(blank=True, help_text='Kế hoạch điều trị')),
                ('follow_up_date', models.DateField(blank=True, help_text='Ngày tái khám', null=True)),
                ('follow_up_reason', models.TextField(blank=True, help_text='Lý do tái khám')),
                ('attachments', models.FileField(blank=True, help_text='File đính kèm (kết quả xét nghiệm, ảnh...)', upload_to='medical_records/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointments.appointment')),
            ],
            options={
                'verbose_name': 'Hồ sơ khám bệnh',
                'verbose_name_plural': 'Hồ sơ khám bệnh',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(help_text='Tên thuốc', max_length=200)),
                ('dosage', models.CharField(help_text='Liều lượng (VD: 1 viên/lần)', max_length=100)),
                ('frequency', models.CharField(help_text='Tần suất (VD: 3 lần/ngày)', max_length=100)),
                ('duration', models.CharField(help_text='Thời gian (VD: 7 ngày)', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Hướng dẫn sử dụng')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointments.medicalrecord')),
            ],
            options={
                'verbose_name': 'Đơn thuốc',
                'verbose_name_plural': 'Đơn thuốc',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(help_text='Ngày mong muốn')),
                ('preferred_time_slots', models.JSONField(blank=True, default=list, help_text='Danh sách khung giờ mong muốn, ví dụ: ["08:00", "09:00"]')),
                ('status', models.CharField(choices=[('waiting', 'Đang chờ'), ('notified', 'Đã thông báo'), ('booked', 'Đã đặt'), ('expired', 'Hết hạn')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Ghi chú của bệnh nhân')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Danh sách chờ',
                'verbose_name_plural': 'Danh sách chờ',
                'ordering': ['-created_at'],
            },
        ),
    ]
