# Generated by Copilot on 2026-04-19

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_checked_in_appointment_checked_in_at_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(
                fields=('doctor', 'appointment_date', 'appointment_time'),
                condition=Q(status__in=['pending', 'confirmed']),
                name='uniq_active_appointment_slot',
            ),
        ),
    ]
