# Generated by Django 6.0.3 on 2026-04-18 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_checked_in_appointment_checked_in_at_and_more'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.TextField(blank=True, help_text='Địa chỉ phòng khám'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_map_url',
            field=models.URLField(blank=True, help_text='URL Google Maps iframe'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_name',
            field=models.CharField(blank=True, help_text='Tên phòng khám', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='clinic_phone',
            field=models.CharField(blank=True, help_text='Số điện thoại phòng khám', max_length=15),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=5, help_text='Thời gian nghỉ giữa các ca (phút)'),
        ),
        migrations.CreateModel(
            name='DoctorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, help_text='Tên bệnh nhân (nếu đặt lịch)', max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')], help_text='Điểm đánh giá (1-5 sao)')),
                ('comment', models.TextField(blank=True, help_text='Nhận xét của bệnh nhân')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Đánh giá bác sĩ',
                'verbose_name_plural': 'Đánh giá bác sĩ',
                'ordering': ['-created_at'],
            },
        ),
    ]
